### ISSUE TITLE
Error when run 

### ISSUE THREAD

**Issue by akilinomendez** [ofkindness/winston-pg-native#9]
Hi when run program throw Error:

const loggerdb = new Logger({
                 ^

TypeError: Logger is not a constructor

**Comment by ofkindness** [comment]
Hi @akilinomendez, sorry for late response, did you required it properly? 
```const { Logger } = require('winston');```

Please check here for example https://github.com/ofkindness/winston-pg-native/blob/master/test/winston-pg-native-test.js
